name: Build and Test ICU4C

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-icu4c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ICU4C
        run: |
          # Create necessary directories
          mkdir -p dist
          touch dist/build.log
          
          # Run the full build script
          ./full-build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: icu4c-build-artifacts
          path: |
            dist/build.log
            dist/*.zip
          retention-days: 7

  test-linux-x86_64:
    needs: build-icu4c
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: icu4c-build-artifacts
          path: dist

      - name: Run tests for Linux x86_64
        run: |
          cd test/test-linux-x86_64
          ./run.sh

  # Add more jobs for other platforms as needed
  # For example:
  # build-and-test-windows-x86_64:
  #   runs-on: windows-latest
  #   steps:
  #     ...

  # build-and-test-wasm:
  #   runs-on: ubuntu-latest
  #   steps:
  #     ...
