name: Build and Test ICU4C

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux-64:
    name: Build Linux 64
    runs-on: ubuntu-latest
    outputs:
      linux-artifact-name: linux-build-artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux ICU4C 64
        run: |
          mkdir -p dist
          touch dist/build.log
          WORDDIR=dist DISTDIR=dist ./full-build.sh --linux-64

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts-64
          path: |
            dist/
          retention-days: 7

  build-linux-32:
    name: Build Linux 32
    runs-on: ubuntu-latest
    outputs:
      linux-artifact-name: linux-build-artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux ICU4C 32
        run: |
          mkdir -p dist
          touch dist/build.log
          WORDDIR=dist DISTDIR=dist ./full-build.sh --linux-32

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts-32
          path: |
            dist/
          retention-days: 7

  build-windows-64:
    name: Build Windows 64
    needs: build-linux-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-64
          path: dist

      - name: Build Windows ICU4C
        run: |
          WORDDIR=dist DISTDIR=dist ./full-build.sh --win-64

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts-64
          path: |
            dist/
          retention-days: 7

  build-windows-32:
    name: Build Windows 32
    needs: build-linux-32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-32
          path: dist

      - name: Build Windows ICU4C
        run: |
          WORDDIR=dist DISTDIR=dist ./full-build.sh --win-32

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts-32
          path: |
            dist/
          retention-days: 7

  # build-wasm:
  #   name: Build WASM (32/64)
  #   needs: build-linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Download Linux build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: linux-build-artifacts
  #         path: dist

  #     - name: Build WASM ICU4C
  #       run: |
  #         ./full-build.sh --wasm-32 --wasm-64

  #     - name: Upload WASM artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: wasm-build-artifacts
  #         path: |
  #           dist/
  #         retention-days: 7

  # build-llvmir:
  #   name: Build LLVM IR (32/64)
  #   needs: build-linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Download Linux build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: linux-build-artifacts
  #         path: dist

  #     - name: Build LLVM IR
  #       run: |
  #         ./full-build.sh --llvm-32 --llvm-64

  #     - name: Upload LLVM IR artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: llvmir-build-artifacts
  #         path: |
  #           dist/
  #         retention-days: 7

  # test-linux-x86_64:
  #   name: Test Linux x86_64
  #   needs: build-linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Download Linux build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: linux-build-artifacts
  #         path: dist

  #     - name: Run Linux x86_64 Tests
  #       run: |
  #         cd test/test-linux-x86_64
  #         ./run.sh

  # test-linux-x86_32:
  #   name: Test Linux x86_32
  #   needs: build-linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Download Linux build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: linux-build-artifacts
  #         path: dist

  #     - name: Run Linux x86_32 Tests
  #       run: |
  #         cd test/test-linux-x86_32
  #         ./run.sh
