name: Build and Test ICU4C

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:

  build-linux-32:
    name: Build Linux 32
    runs-on: ubuntu-latest
    outputs:
      linux-artifact-name: linux-build-artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux ICU4C 32
        run: |
          mkdir -p dist
          touch dist/build.log
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --linux-32

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts-32
          path: |
            build/
          retention-days: 7

      - name: Upload Linux dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist-artifacts-32
          path: |
            dist/
          retention-days: 7

      - name: Upload Linux dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-32.zip
          path: dist/*_linux-*-32_*.zip
          retention-days: 7

  build-linux-64:
    name: Build Linux 64
    runs-on: ubuntu-latest
    outputs:
      linux-artifact-name: linux-build-artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux ICU4C 64
        run: |
          mkdir -p dist
          touch dist/build.log
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --linux-64

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts-64
          path: |
            build/
          retention-days: 7

      - name: Upload Linux dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist-artifacts-64
          path: |
            dist/
          retention-days: 7

      - name: Upload Linux dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-64.zip
          path: dist/*_linux-*-64_*.zip
          retention-days: 7

  macos:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake --formula
          brew list ninja || brew install ninja

      - name: Prepare ICU source
        run: |
          WORKDIR=$(pwd)/build
          DISTDIR=$(pwd)/dist
          BUILDLOG="$DISTDIR/build.log"

          echo "==========================================================================="
          echo "\033[0;32m Detail build log can be found at: $BUILDLOG\033[0m"
          echo "==========================================================================="

          mkdir -p  "$WORKDIR"
          mkdir -p  "$DISTDIR"
          touch     "$BUILDLOG"
          echo "" > "$BUILDLOG"
          ./build.sh --prepare-only

      - name: Build macOS Release
        run: |
          echo "Building macOS release for version $VERSION"
          chmod +x mac-build.sh || true

          # mac-build.sh does not concern the QUICK_BUILD variable.
          ./mac-build.sh

      # - name: Upload macOS Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: macos-packages
      #     path: dist/*.zip
      #     if-no-files-found: error

  build-windows-32:
    name: Build Windows 32
    needs: build-linux-32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-32
          path: build

      - name: Download Linux dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-32
          path: dist

      - name: Build Windows ICU4C
        run: |
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --win-32

      - name: Upload Windows dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-32.zip
          path: dist/*_windows-*-32_*.zip
          retention-days: 7

  build-windows-64:
    name: Build Windows 64
    needs: build-linux-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-64
          path: build

      - name: Download Linux dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-64
          path: dist

      - name: Build Windows ICU4C
        run: |
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --win-64

      - name: Upload Windows dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-64.zip
          path: dist/*_windows-*-64_*.zip
          retention-days: 7

  build-wasm-32:
    name: Build WASM 32
    needs: build-linux-32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-32
          path: build

      - name: Download Linux dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-32
          path: dist

      - name: Build WASM ICU4C
        run: |
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --wasm-32

      - name: Upload WASM dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-32.zip
          path: dist/*_wasm-*-32_*.zip
          retention-days: 7

  build-wasm-64:
    name: Build WASM 64
    needs: build-linux-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts-64
          path: build

      - name: Download Linux dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-64
          path: dist

      - name: Build WASM ICU4C
        run: |
          WORDDIR=$(pwd)/dist DISTDIR=$(pwd)/dist ./full-build.sh --wasm-64

      - name: Upload WASM dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-64.zip
          path: dist/*_wasm-*-64_*.zip
          retention-days: 7

  test-linux-x86_32:
    name: Test Linux x86_32
    needs: build-linux-32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-32
          path: dist

      - name: Run Linux x86_32 Tests
        run: |
          cd test/test-linux-x86_32
          ./run.sh


  test-linux-x86_64:
    name: Test Linux x86_64
    needs: build-linux-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist-artifacts-64
          path: dist

      - name: Run Linux x86_64 Tests
        run: |
          cd test/test-linux-x86_64
          ./run.sh

  test-windows-x64:
    name: Test Windows x64
    needs: build-windows-64
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Visual Studio environment
        uses: microsoft/setup-msbuild@v1.1

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-64.zip
          path: dist

      - name: Run Windows x64 Tests
        run: |
          cd test\test-windows-x64
          .\run.bat
        shell: cmd

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-test-logs
          path: |
            ${{ runner.temp }}\icu4c-test\build\*.log
            ${{ runner.temp }}\icu4c-test\build\CMakeFiles\CMakeOutput.log
            ${{ runner.temp }}\icu4c-test\build\CMakeFiles\CMakeError.log